services:
  - type: web
    name: figma-clone
    runtime: static
    autoDeploy: true
    buildCommand: cd frontend && npm install --legacy-peer-deps --no-audit --no-fund && npm run build:render
    staticPublishPath: frontend/out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
